-- Initiatives: project themes that group issues (one initiative per issue)

create table if not exists public.initiatives (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects (id) on delete cascade,
  name text not null,
  description text not null default '',
  status text not null default 'planned' check (status in ('planned', 'active', 'done')),
  target_date date,
  unique (project_id, name)
);

alter table public.issues
  add column if not exists initiative_id bigint references public.initiatives (id) on delete set null;

alter table public.initiatives enable row level security;

drop policy if exists initiatives_via_project on public.initiatives;
create policy initiatives_via_project on public.initiatives
  for all using (project_id in (select public.my_project_ids()))
  with check (project_id in (select public.my_project_ids()));
