-- Directed issue links within a project: blocks, relates, duplicates

create table if not exists public.issue_links (
  id bigint generated by default as identity primary key,
  source_id bigint not null references public.issues (id) on delete cascade,
  target_id bigint not null references public.issues (id) on delete cascade,
  link_type text not null check (link_type in ('blocks', 'relates', 'duplicates')),
  unique (source_id, target_id, link_type),
  check (source_id <> target_id)
);

alter table public.issue_links enable row level security;

drop policy if exists issue_links_via_issue on public.issue_links;
create policy issue_links_via_issue on public.issue_links
  for all using (
    exists (
      select 1 from public.issues s
      join public.issues t on t.id = target_id
      where s.id = source_id
        and s.project_id = t.project_id
        and s.project_id in (select public.my_project_ids())
    )
  ) with check (
    exists (
      select 1 from public.issues s
      join public.issues t on t.id = target_id
      where s.id = source_id
        and s.project_id = t.project_id
        and s.project_id in (select public.my_project_ids())
    )
  );
