-- Flat checklist items on issues (no nesting, no assignees)

create table if not exists public.issue_checklist_items (
  id bigint generated by default as identity primary key,
  issue_id bigint not null references public.issues (id) on delete cascade,
  title text not null,
  done boolean not null default false,
  position double precision not null default 0
);

alter table public.issue_checklist_items enable row level security;

drop policy if exists checklist_via_issue on public.issue_checklist_items;
create policy checklist_via_issue on public.issue_checklist_items
  for all using (
    exists (
      select 1 from public.issues i
      where i.id = issue_id and i.project_id in (select public.my_project_ids())
    )
  ) with check (
    exists (
      select 1 from public.issues i
      where i.id = issue_id and i.project_id in (select public.my_project_ids())
    )
  );
