-- OPC Advisor v1 schema + RLS
create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users (id) on delete cascade,
  key text not null unique,
  name text not null,
  description text not null default '',
  next_sequence integer not null default 1,
  created_at timestamptz not null default now()
);

create table if not exists public.project_columns (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects (id) on delete cascade,
  name text not null,
  state_type text not null check (state_type in ('backlog', 'unstarted', 'started', 'completed', 'canceled')),
  position integer not null,
  unique (project_id, position)
);

create table if not exists public.labels (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects (id) on delete cascade,
  name text not null,
  color text not null default '#6b7280',
  unique (project_id, name)
);

create table if not exists public.cycles (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects (id) on delete cascade,
  name text not null,
  goal text not null default '',
  start_date date not null,
  end_date date not null,
  completed_at timestamptz,
  check (end_date >= start_date)
);

create table if not exists public.issues (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects (id) on delete cascade,
  sequence_number integer not null,
  column_id bigint not null references public.project_columns (id),
  parent_id bigint references public.issues (id) on delete set null,
  cycle_id bigint references public.cycles (id) on delete set null,
  assignee_id uuid references auth.users (id) on delete set null,
  title text not null,
  description text not null default '',
  start_date date,
  due_date date,
  position double precision not null default 0,
  unique (project_id, sequence_number)
);

create table if not exists public.issue_labels (
  issue_id bigint not null references public.issues (id) on delete cascade,
  label_id bigint not null references public.labels (id) on delete cascade,
  primary key (issue_id, label_id)
);

create table if not exists public.issue_comments (
  id bigint generated by default as identity primary key,
  issue_id bigint not null references public.issues (id) on delete cascade,
  author_id uuid not null references auth.users (id) on delete cascade,
  body text not null,
  created_at timestamptz not null default now()
);

alter table public.projects enable row level security;
alter table public.project_columns enable row level security;
alter table public.labels enable row level security;
alter table public.cycles enable row level security;
alter table public.issues enable row level security;
alter table public.issue_labels enable row level security;
alter table public.issue_comments enable row level security;

create policy projects_owner on public.projects
  for all using (owner_id = auth.uid()) with check (owner_id = auth.uid());

create policy columns_via_project on public.project_columns
  for all using (
    exists (select 1 from public.projects p where p.id = project_id and p.owner_id = auth.uid())
  ) with check (
    exists (select 1 from public.projects p where p.id = project_id and p.owner_id = auth.uid())
  );

create policy labels_via_project on public.labels
  for all using (
    exists (select 1 from public.projects p where p.id = project_id and p.owner_id = auth.uid())
  ) with check (
    exists (select 1 from public.projects p where p.id = project_id and p.owner_id = auth.uid())
  );

create policy cycles_via_project on public.cycles
  for all using (
    exists (select 1 from public.projects p where p.id = project_id and p.owner_id = auth.uid())
  ) with check (
    exists (select 1 from public.projects p where p.id = project_id and p.owner_id = auth.uid())
  );

create policy issues_via_project on public.issues
  for all using (
    exists (select 1 from public.projects p where p.id = project_id and p.owner_id = auth.uid())
  ) with check (
    exists (select 1 from public.projects p where p.id = project_id and p.owner_id = auth.uid())
  );

create policy issue_labels_via_issue on public.issue_labels
  for all using (
    exists (
      select 1 from public.issues i
      join public.projects p on p.id = i.project_id
      where i.id = issue_id and p.owner_id = auth.uid()
    )
  ) with check (
    exists (
      select 1 from public.issues i
      join public.projects p on p.id = i.project_id
      where i.id = issue_id and p.owner_id = auth.uid()
    )
  );

create policy comments_via_issue on public.issue_comments
  for all using (
    exists (
      select 1 from public.issues i
      join public.projects p on p.id = i.project_id
      where i.id = issue_id and p.owner_id = auth.uid()
    )
  ) with check (
    exists (
      select 1 from public.issues i
      join public.projects p on p.id = i.project_id
      where i.id = issue_id and p.owner_id = auth.uid()
    )
  );
