-- Members, invites, and membership-based RLS

create table if not exists public.project_members (
  project_id bigint not null references public.projects (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  role text not null default 'member' check (role in ('owner', 'member')),
  email text not null default '',
  created_at timestamptz not null default now(),
  primary key (project_id, user_id)
);

create table if not exists public.project_invites (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects (id) on delete cascade,
  email text not null,
  role text not null default 'member' check (role in ('owner', 'member')),
  token uuid not null default gen_random_uuid() unique,
  status text not null default 'pending' check (status in ('pending', 'accepted', 'revoked')),
  invited_by uuid references auth.users (id) on delete set null,
  created_at timestamptz not null default now()
);

create unique index if not exists project_invites_pending_email
  on public.project_invites (project_id, email)
  where status = 'pending';

insert into public.project_members (project_id, user_id, role, email)
select p.id, p.owner_id, 'owner', coalesce(u.email, '')
from public.projects p
left join auth.users u on u.id = p.owner_id
on conflict do nothing;

create or replace function public.my_project_ids()
returns setof bigint
language sql
stable
security definer
set search_path = public
as $$
  select project_id from public.project_members where user_id = auth.uid();
$$;

alter table public.project_members enable row level security;
alter table public.project_invites enable row level security;

create policy members_via_membership on public.project_members
  for select using (project_id in (select public.my_project_ids()));

create policy members_insert_self on public.project_members
  for insert with check (
    user_id = auth.uid()
    and (
      (
        role = 'owner'
        and exists (
          select 1 from public.projects p
          where p.id = project_id and p.owner_id = auth.uid()
        )
      )
      or exists (
        select 1 from public.project_invites i
        where i.project_id = project_members.project_id
          and i.status = 'pending'
          and lower(i.email) = lower(coalesce(auth.jwt() ->> 'email', ''))
      )
    )
  );

create policy members_owner_write on public.project_members
  for all using (
    project_id in (
      select project_id from public.project_members
      where user_id = auth.uid() and role = 'owner'
    )
  ) with check (
    project_id in (
      select project_id from public.project_members
      where user_id = auth.uid() and role = 'owner'
    )
  );

-- Avoid recursion on owner write: use definer helper
create or replace function public.is_project_owner(pid bigint)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.project_members
    where project_id = pid and user_id = auth.uid() and role = 'owner'
  );
$$;

drop policy if exists members_owner_write on public.project_members;

create policy members_owner_update on public.project_members
  for update using (public.is_project_owner(project_id))
  with check (public.is_project_owner(project_id));

create policy members_owner_delete on public.project_members
  for delete using (public.is_project_owner(project_id));

create policy invites_select on public.project_invites
  for select using (
    project_id in (select public.my_project_ids())
    or (status = 'pending' and lower(email) = lower(coalesce(auth.jwt() ->> 'email', '')))
  );

create policy invites_owner_insert on public.project_invites
  for insert with check (public.is_project_owner(project_id));

create policy invites_owner_update on public.project_invites
  for update using (public.is_project_owner(project_id) or (status = 'pending' and lower(email) = lower(coalesce(auth.jwt() ->> 'email', ''))))
  with check (public.is_project_owner(project_id) or (status = 'pending' and lower(email) = lower(coalesce(auth.jwt() ->> 'email', ''))));

drop policy if exists projects_owner on public.projects;
create policy projects_access on public.projects
  for select using (id in (select public.my_project_ids()) or owner_id = auth.uid());
create policy projects_insert_owner on public.projects
  for insert with check (owner_id = auth.uid());
create policy projects_update_member on public.projects
  for update using (id in (select public.my_project_ids()))
  with check (id in (select public.my_project_ids()));
create policy projects_delete_owner on public.projects
  for delete using (public.is_project_owner(id) or owner_id = auth.uid());

drop policy if exists columns_via_project on public.project_columns;
create policy columns_via_project on public.project_columns
  for all using (project_id in (select public.my_project_ids()))
  with check (project_id in (select public.my_project_ids()));

drop policy if exists labels_via_project on public.labels;
create policy labels_via_project on public.labels
  for all using (project_id in (select public.my_project_ids()))
  with check (project_id in (select public.my_project_ids()));

drop policy if exists cycles_via_project on public.cycles;
create policy cycles_via_project on public.cycles
  for all using (project_id in (select public.my_project_ids()))
  with check (project_id in (select public.my_project_ids()));

drop policy if exists issues_via_project on public.issues;
create policy issues_via_project on public.issues
  for all using (project_id in (select public.my_project_ids()))
  with check (project_id in (select public.my_project_ids()));

drop policy if exists issue_labels_via_issue on public.issue_labels;
create policy issue_labels_via_issue on public.issue_labels
  for all using (
    exists (
      select 1 from public.issues i
      where i.id = issue_id and i.project_id in (select public.my_project_ids())
    )
  ) with check (
    exists (
      select 1 from public.issues i
      where i.id = issue_id and i.project_id in (select public.my_project_ids())
    )
  );

drop policy if exists comments_via_issue on public.issue_comments;
create policy comments_via_issue on public.issue_comments
  for all using (
    exists (
      select 1 from public.issues i
      where i.id = issue_id and i.project_id in (select public.my_project_ids())
    )
  ) with check (
    exists (
      select 1 from public.issues i
      where i.id = issue_id and i.project_id in (select public.my_project_ids())
    )
  );
