create table if not exists public.saved_views (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects (id) on delete cascade,
  name text not null,
  kind text not null check (kind in ('kanban', 'table', 'timeline', 'calendar')),
  spec jsonb not null default '{}'::jsonb,
  position integer not null default 0,
  created_by uuid references auth.users (id) on delete set null,
  unique (project_id, name)
);

alter table public.saved_views enable row level security;

drop policy if exists saved_views_via_project on public.saved_views;
create policy saved_views_via_project on public.saved_views
  for all using (project_id in (select public.my_project_ids()))
  with check (project_id in (select public.my_project_ids()));
