-- Issue types, priority, estimates

create table if not exists public.issue_types (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects (id) on delete cascade,
  name text not null,
  color text not null default '#6b7280',
  position integer not null default 0,
  unique (project_id, name)
);

alter table public.issues
  add column if not exists type_id bigint references public.issue_types (id) on delete set null,
  add column if not exists priority text check (priority is null or priority in ('p0', 'p1', 'p2', 'p3')),
  add column if not exists estimate_points double precision check (estimate_points is null or estimate_points >= 0),
  add column if not exists estimate_minutes integer check (estimate_minutes is null or estimate_minutes >= 0);

insert into public.issue_types (project_id, name, color, position)
select p.id, 'Task', '#3b82f6', 0
from public.projects p
where not exists (
  select 1 from public.issue_types t where t.project_id = p.id and t.name = 'Task'
);

insert into public.issue_types (project_id, name, color, position)
select p.id, 'Bug', '#ef4444', 1
from public.projects p
where not exists (
  select 1 from public.issue_types t where t.project_id = p.id and t.name = 'Bug'
);

alter table public.issue_types enable row level security;

drop policy if exists issue_types_via_project on public.issue_types;
create policy issue_types_via_project on public.issue_types
  for all using (project_id in (select public.my_project_ids()))
  with check (project_id in (select public.my_project_ids()));
